name: Deploy Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t my-fastapi-app .

      - name: Push Docker image to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker tag my-fastapi-app mydockerusername/my-fastapi-app:latest
          docker push mydockerusername/my-fastapi-app:latest

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no user@your-server-ip "docker pull mydockerusername/my-fastapi-app:latest && docker-compose down && docker-compose up -d"
